
ENABLE_DEBUG_BREAKPOINTS = True

USE_GPU = True
MULTI_GPU = True #True
RANDOM_SEED = 42
RANDOM_SPLIT = False
TEST_SIZE_FOR_RS = 0.2
SMALL_DATA = False #True

DIFF_TRAIN_SIZE_RATIO = 0.75

MIN_AGE = 15
MAX_AGE = 80
AGE_INTERVAL = 1
AGE_RADIUS = 35
AGE_DIFF_LEARN_RADIUS_HI = 10 # 35
AGE_DIFF_LEARN_RADIUS_LO = 4 # 0

BATCH_SIZE = 32 #16
NUM_EPOCHS = 200
NUM_ITERS = int(1.5e5)
LEARNING_RATE = 0.0003 #0.0001

VALIDATION_PERIOD_ITERS = 120
VALIDATE_AT_END_OF_EPOCH = True

UNFREEZE_FEATURE_EXT_EPOCH = 10 # 0 10
UNFREEZE_FEATURE_EXT_ON_RLVNT_EPOCH = True

NUM_OF_COPIES_AGE_PREDICT = 10
MID_FEATURE_SIZE_AGE_PREDICT = 1024

NUM_OF_WORKERS_DATALOADER = 4
if ENABLE_DEBUG_BREAKPOINTS:
    NUM_OF_WORKERS_DATALOADER = 0


OPTIMIZER = "RangerLars" # "RangerLars" / "Adam"
SCHEDULER = "CosineAnnealingLR+GradualWarmupSchedule" #"CosineAnnealingLR+GradualWarmupScheduler" / "NoScheduler" 


DEEP_MODEL = False

CHECK_DIFF_BASED = True