
ENABLE_DEBUG_BREAKPOINTS = True #True

USE_GPU = True #True
MULTI_GPU = True #True
RANDOM_SEED = 42
RANDOM_SPLIT = False
TEST_SIZE_FOR_RS = 0.2
SMALL_DATA = True #False

DIFF_TRAIN_SIZE_RATIO = 0.75

MIN_AGE = 15
MAX_AGE = 80
AGE_INTERVAL = 1
AGE_RADIUS = 35
APREF_VLD_SET_AGE_DIFF_LEARN_RADIUS_HI = 3
APREF_VLD_SET_AGE_DIFF_LEARN_RADIUS_LO = 0
AGE_DIFF_LEARN_RADIUS_HI = 3 #35 #10
AGE_DIFF_LEARN_RADIUS_LO = 0 #4

BATCH_SIZE = 64 #32 #32
NUM_EPOCHS = 60 #60
NUM_ITERS = int(1.5e5)
LEARNING_RATE = 0.0003 #03

VALIDATION_PERIOD_ITERS = 400
VALIDATE_AT_END_OF_EPOCH = True

UNFREEZE_FEATURE_EXT_EPOCH = 15 #10
UNFREEZE_FEATURE_EXT_ON_RLVNT_EPOCH = True

NUM_OF_COPIES_AGE_PREDICT = 10
MID_FEATURE_SIZE_AGE_PREDICT = 1024

NUM_OF_WORKERS_DATALOADER = 4
if ENABLE_DEBUG_BREAKPOINTS:
    NUM_OF_WORKERS_DATALOADER = 0


OPTIMIZER = "RangerLars" # "RangerLars" / "Adam"
SCHEDULER = "CosineAnnealingLR+GradualWarmupScheduler" # "NoScheduler" # 


DEEP_MODEL = True

CHECK_DIFF_BASED = True #True

NUM_OF_REFS = 1