
ENABLE_DEBUG_BREAKPOINTS = False

USE_GPU = True
MULTI_GPU = True
RANDOM_SEED = 42
RANDOM_SPLIT = False
TEST_SIZE_FOR_RS = 0.2
SMALL_DATA = False

DIFF_TRAIN_SIZE_RATIO = 0.75

MIN_AGE = 15
MAX_AGE = 80
AGE_INTERVAL = 1
AGE_RADIUS = 35

BATCH_SIZE = 64
NUM_EPOCHS = 60
NUM_ITERS = int(1.5e5)
LEARNING_RATE = 0.0003 #03

VALIDATION_PERIOD_ITERS = 100
VALIDATE_AT_END_OF_EPOCH = True

UNFREEZE_FEATURE_EXT_EPOCH = 15
UNFREEZE_FEATURE_EXT_ON_RLVNT_EPOCH = True

NUM_OF_WORKERS_DATALOADER = 4
if ENABLE_DEBUG_BREAKPOINTS:
    NUM_OF_WORKERS_DATALOADER = 0


OPTIMIZER = "Adam" # "RangerLars" / "Adam"
SCHEDULER = "CosineAnnealingLR+GradualWarmupScheduler" # "NoScheduler" # 

NUM_OF_COPIES_AGE_PREDICT = 10
MID_FEATURE_SIZE_AGE_PREDICT = 1024




CHECK_DIFF_BASED = False